export const internships = [
  {
    id: 1,
    title: "Java Developer",
    status: "Active",
    views: 17232,
    applications: 985,
    shared: true,
    date: "14 April 2025",
  },
  {
    id: 2,
    title: "Java Developer",
    status: "Closed",
    views: 17232,
    applications: 985,
    shared: true,
    date: "14 April 2025",
  },
  {
    id: 3,
    title: "Java Developer",
    status: "Closed",
    views: 17232,
    applications: 985,
    shared: true,
    date: "14 April 2025",
  },
  {
    id: 4,
    title: "Java Developer",
    status: "Closed",
    views: 17232,
    applications: 985,
    shared: true,
    date: "14 April 2025",
  },
  {
    id: 5,
    title: "Java Developer",
    status: "Closed",
    views: 17232,
    applications: 985,
    shared: true,
    date: "14 April 2025",
  },
];
